"""
Build the shared theme's brand assets from the official AFRIFF logo.

Source (downloaded from afriff.com, kept in brand/source/):
  afriff-logo-main.jpg  — stacked logo: emblem, AFRIFF wordmark, festival name

Outputs:
  brand/derived/emblem.png, wordmark.svg, subline.svg
  layers/ui-kit/public/brand/afriff-emblem-{96,192,384}.webp
  layers/ui-kit/public/{pwa-*,maskable-icon-512x512,apple-touch-icon}.png, favicon.ico, favicon.svg
  layers/ui-kit/components/brand/BrandWordmark.vue, BrandSubline.vue

Run from the repo root:
  pip install pillow numpy potracer
  python3 brand/scripts/build_brand_assets.py

When AFRIFF supplies official vector artwork, prefer it over these traced versions.
"""

import base64
import io
import re
from pathlib import Path

import numpy as np
import potrace
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'brand/source/afriff-logo-main.jpg'
DERIVED = ROOT / 'brand/derived'
PUBLIC = ROOT / 'layers/ui-kit/public'
COMPONENTS = ROOT / 'layers/ui-kit/components/brand'

NAVY = (10, 16, 66, 255)  # #0A1042 — wordmark colour sampled from the logo

DERIVED.mkdir(parents=True, exist_ok=True)
(PUBLIC / 'brand').mkdir(parents=True, exist_ok=True)

src = Image.open(SOURCE).convert('RGB')
arr = np.asarray(src).astype(np.float32)


# ---------------------------------------------------------------- emblem

def cut_emblem() -> Image.Image:
    ink = (765 - arr.sum(axis=2)) > 60
    ys, xs = np.where(ink[:760])  # emblem sits above the wordmark
    x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    r = min(x1 - x0, y1 - y0) / 2
    radius = r - 1.5  # inset so no white JPEG fringe survives
    size = int(np.ceil(2 * r)) + 2
    left, top = int(round(cx - size / 2)), int(round(cy - size / 2))
    crop = src.crop((left, top, left + size, top + size)).convert('RGBA')
    ss = 4  # supersampled anti-aliased circular mask
    mask = Image.new('L', (size * ss, size * ss), 0)
    c = size / 2
    ImageDraw.Draw(mask).ellipse([(c - radius) * ss, (c - radius) * ss, (c + radius) * ss, (c + radius) * ss], fill=255)
    crop.putalpha(mask.resize((size, size), Image.LANCZOS))
    return crop


# ---------------------------------------------------------------- vector trace

def trace(region: tuple[int, int, int, int]) -> tuple[str, str]:
    x0, y0, x1, y1 = region
    sub = arr[y0:y1, x0:x1]
    lum = 0.2126 * sub[..., 0] + 0.7152 * sub[..., 1] + 0.0722 * sub[..., 2]
    bitmap = potrace.Bitmap(lum >= 127.5)  # potracer fills the False (dark) pixels
    paths = bitmap.trace(turdsize=4, alphamax=1.0, opticurve=True, opttolerance=0.2)
    parts, xs, ys = [], [], []
    fmt = lambda p: f'{p.x:.1f} {p.y:.1f}'
    for curve in paths:
        parts.append('M' + fmt(curve.start_point))
        for seg in curve.segments:
            if seg.is_corner:
                parts.append('L' + fmt(seg.c) + 'L' + fmt(seg.end_point))
                pts = [seg.c, seg.end_point]
            else:
                parts.append('C' + fmt(seg.c1) + ' ' + fmt(seg.c2) + ' ' + fmt(seg.end_point))
                pts = [seg.end_point]
            xs += [p.x for p in pts]
            ys += [p.y for p in pts]
        parts.append('Z')
    view_box = f'{min(xs):.1f} {min(ys):.1f} {max(xs) - min(xs):.1f} {max(ys) - min(ys):.1f}'
    return view_box, ''.join(parts)


def svg(view_box: str, d: str) -> str:
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" fill="currentColor"><path fill-rule="evenodd" d="{d}"/></svg>\n'


def component(doc: str, label: str, view_box: str, d: str) -> str:
    return f'''<script setup lang="ts">
/**
 * {doc}
 * Generated by brand/scripts/build_brand_assets.py — do not edit by hand.
 */
</script>

<template>
  <svg viewBox="{view_box}" fill="currentColor" role="img" aria-label="{label}">
    <path fill-rule="evenodd" d="{d}" />
  </svg>
</template>
'''


# ---------------------------------------------------------------- icons

def rounded(size: int, radius: int, color) -> Image.Image:
    ss = 4
    mask = Image.new('L', (size * ss, size * ss), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, size * ss - 1, size * ss - 1], radius * ss, fill=255)
    bg = Image.new('RGBA', (size, size), color)
    bg.putalpha(mask.resize((size, size), Image.LANCZOS))
    return bg


def icon(emblem: Image.Image, size: int, scale: float, is_rounded: bool) -> Image.Image:
    bg = rounded(size, int(size * 0.22), NAVY) if is_rounded else Image.new('RGBA', (size, size), NAVY)
    e = emblem.resize((round(size * scale),) * 2, Image.LANCZOS)
    bg.alpha_composite(e, ((size - e.width) // 2, (size - e.height) // 2))
    return bg


def save_quantized(img: Image.Image, path: Path) -> None:
    img.convert('RGBA').quantize(256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.FLOYDSTEINBERG).save(path, optimize=True)


def main() -> None:
    emblem = cut_emblem()
    emblem.save(DERIVED / 'emblem.png', optimize=True)

    word_vb, word_d = trace((40, 780, 1960, 1230))
    sub_vb, sub_d = trace((40, 1270, 1960, 1380))
    (DERIVED / 'wordmark.svg').write_text(svg(word_vb, word_d))
    (DERIVED / 'subline.svg').write_text(svg(sub_vb, sub_d))
    COMPONENTS.mkdir(parents=True, exist_ok=True)
    (COMPONENTS / 'BrandWordmark.vue').write_text(component(
        '"AFRIFF" wordmark traced from the official logo (currentColor: navy in light theme, white in dark).',
        'AFRIFF', word_vb, word_d))
    (COMPONENTS / 'BrandSubline.vue').write_text(component(
        '"AFRICA INTERNATIONAL FILM FESTIVAL" line traced from the official logo (currentColor).',
        'Africa International Film Festival', sub_vb, sub_d))

    for s in (96, 192, 384):
        emblem.resize((s, s), Image.LANCZOS).save(PUBLIC / f'brand/afriff-emblem-{s}.webp', quality=90, method=6)

    save_quantized(icon(emblem, 64, 0.84, True), PUBLIC / 'pwa-64x64.png')
    save_quantized(icon(emblem, 192, 0.84, True), PUBLIC / 'pwa-192x192.png')
    save_quantized(icon(emblem, 512, 0.84, True), PUBLIC / 'pwa-512x512.png')
    save_quantized(icon(emblem, 512, 0.62, False), PUBLIC / 'maskable-icon-512x512.png')  # inside the maskable safe zone
    save_quantized(icon(emblem, 180, 0.78, False), PUBLIC / 'apple-touch-icon.png')

    emblem.resize((256, 256), Image.LANCZOS).save(PUBLIC / 'favicon.ico', sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])
    buf = io.BytesIO()
    emblem.resize((64, 64), Image.LANCZOS).save(buf, 'PNG', optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode()
    (PUBLIC / 'favicon.svg').write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
        f'<image width="64" height="64" href="data:image/png;base64,{b64}"/></svg>\n')
    print('Brand assets rebuilt from', SOURCE.relative_to(ROOT))


if __name__ == '__main__':
    main()
